config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  get 'admins/index'
  get 'admins/show'
  get 'admins/new'
  post 'admins/create'
  get 'admins/edit'
  put 'admins/update'
  delete 'admins/destroy'

  get 'doctors/index'
  get 'doctors/show'
  get 'doctors/new'
  post 'doctors/create'
  get 'doctors/edit'
  put 'doctors/update'
  delete 'doctors/destroy'

  get 'nurses/index'
  get 'nurses/show'
  get 'nurses/new'
  post 'nurses/create'
  get 'nurses/edit'
  put 'nurses/update'
  delete 'nurses/destroy'

  get 'receptionists/index'
  get 'receptionists/show'
  get 'receptionists/new'
  post 'receptionists/create'
  get 'receptionists/edit'
  put 'receptionists/update'
  delete 'receptionists/destroy'

  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  post 'patients/create'
  get 'patients/edit'
  put 'patients/update'
  delete 'patients/destroy'

  get 'rooms/index'
  get 'rooms/show'
  get 'rooms/new'
  post 'rooms/create'
  get 'rooms/edit'
  put 'rooms/update'
  delete 'rooms/destroy'

  get 'schedules/index'
  get 'schedules/show'
  get 'schedules/new'
  post 'schedules/create'
  get 'schedules/edit'
  put 'schedules/update'
  delete 'schedules/destroy'

  get 'medical_visits/index'
  get 'medical_visits/show'
  get 'medical_visits/new'
  post 'medical_visits/create'
  get 'medical_visits/edit'
  put 'medical_visits/update'
  delete 'medical_visits/destroy'
  get 'medical_visits/doctor_visits'
  get 'medical_visits/patient_change'

  get 'examinations/index'
  get 'examinations/show'
  get 'examinations/new'
  post 'examinations/create'
  get 'examinations/edit'
  put 'examinations/update'
  delete 'examinations/destroy'

  get 'medicines/show'
  get 'medicines/info'

  resources :medical_visits, only: [] do
    resources :visit_descriptions, :prescriptions
  end
  resources :examinations, only: [] do
    resources :examinationpositions
  end
  resources :users, only: [] do
    resources :chronic_diseases, :chronic_medicines, :alergic_medicines
  end

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords",  registrations: "users/registrations" }

  devise_scope :user do
    get "/login" => "users/sessions#new"
  end

  resources :admins, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :doctors, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :nurses, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :receptionists, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :patients, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :medical_visits, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

  resources :examinations, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

end

app/views/layouts/menus/_adminmenu.html.erb
<div id="menudiv">
	<ul class="nav nav-pills nav-justified">
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "home" %>" ><%= link_to "Strona domowa", home_index_path %></li>
	  <li role="presentation" class="dropdown <%= "active" if controller.controller_name == "admins" or
	  																												controller.controller_name == "doctors" or
	  																												controller.controller_name == "nurses" or
	  																												controller.controller_name == "receptionists" or
	  																												controller.controller_name == "patients" %>">
	    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	      Użytkownicy <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu nav nav-pills nav-stacked">
	    	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "admins" %>"><%= link_to "Administratorzy", admins_index_path %></li>
	    	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "doctors" %>"><%= link_to "Lekarze", doctors_index_path %></li>
	    	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "nurses" %>"><%= link_to "Pielęgniarki", nurses_index_path %></li>
	    	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "receptionists" %>"><%= link_to "Recepcjonistki", receptionists_index_path %></li>
	    	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "patients" %>"><%= link_to "Pacjenci", patients_index_path %></li>
	    </ul>
  	</li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "rooms" %>" ><%= link_to "Gabinety", rooms_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "schedules" %>" ><%= link_to "Grafik", schedules_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "medical_visits" or controller.controller_name == "prescriptions" or controller.controller_name == "visit_descriptions" %>" ><%= link_to "Wizyty", medical_visits_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "examinations" or controller.controller_name == "examinationpositions"%>" ><%= link_to "Wyniki badań", examinations_index_path %></li>
	</ul>
</div>

app/views/layouts/menus/_doctormenu.html.erb
<div id="menudiv">
	<ul class="nav nav-pills nav-justified">
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "home" %>" ><%= link_to "Strona domowa", home_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "medical_visits" or controller.controller_name == "prescriptions" or controller.controller_name == "visit_descriptions" %>" ><%= link_to "Wizyty", medical_visits_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "schedules" %>" ><%= link_to "Grafik", schedules_index_path %></li>
  	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "patients" %>"><%= link_to "Pacjenci", patients_index_path %></li>
  	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "examinations" or controller.controller_name == "examinationpositions"%>" ><%= link_to "Wyniki badań", examinations_index_path %></li>
	</ul>
</div>

app/views/layouts/menus/_nursemenu.html.erb
<div id="menudiv">
	<ul class="nav nav-pills nav-justified">
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "home" %>" ><%= link_to "Strona domowa", home_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "examinations" or controller.controller_name == "examinationpositions"%>" ><%= link_to "Wyniki badań", examinations_index_path %></li>
	</ul>
</div>

app/views/layouts/menus/_patientmenu.html.erb
<div id="menudiv">
	<ul class="nav nav-pills nav-justified">
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "home" %>" ><%= link_to "Strona domowa", home_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "medical_visits" or controller.controller_name == "prescriptions" %>" ><%= link_to "Wizyty", medical_visits_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "schedules" %>" ><%= link_to "Grafik", schedules_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "examinations" or controller.controller_name == "examinationpositions"%>" ><%= link_to "Wyniki badań", examinations_index_path %></li>
</div>

app/views/layouts/menus/_receptionistmenu.html.erb
<div id="menudiv">
	<ul class="nav nav-pills nav-justified">
	  <ul class="nav nav-pills nav-justified">
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "home" %>" ><%= link_to "Strona domowa", home_index_path %></li>
	  <li role="presentation" class="dropdown <%= "active" if controller.controller_name == "doctors" or
	  																												controller.controller_name == "patients" %>">
	    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
	      Użytkownicy <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu nav nav-pills nav-stacked">
	    	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "patients" %>"><%= link_to "Pacjenci", patients_index_path %></li>
	    	<li role="presentation" class="menuitem <%= "active" if controller.controller_name == "doctors" %>"><%= link_to "Lekarze", doctors_index_path %></li>
	    </ul>
  	</li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "schedules" %>" ><%= link_to "Grafik", schedules_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "medical_visits" or controller.controller_name == "presentation" %>" ><%= link_to "Wizyty", medical_visits_index_path %></li>
	</ul>
</div>