config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  get 'admins/index'
  get 'admins/show'
  get 'admins/new'
  post 'admins/create'
  get 'admins/edit'
  put 'admins/update'
  delete 'admins/destroy'

  get 'doctors/index'
  get 'doctors/show'
  get 'doctors/new'
  post 'doctors/create'
  get 'doctors/edit'
  put 'doctors/update'
  delete 'doctors/destroy'

  get 'nurses/index'
  get 'nurses/show'
  get 'nurses/new'
  post 'nurses/create'
  get 'nurses/edit'
  put 'nurses/update'
  delete 'nurses/destroy'

  get 'receptionists/index'
  get 'receptionists/show'
  get 'receptionists/new'
  post 'receptionists/create'
  get 'receptionists/edit'
  put 'receptionists/update'
  delete 'receptionists/destroy'

  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  post 'patients/create'
  get 'patients/edit'
  put 'patients/update'
  delete 'patients/destroy'

  get 'rooms/index'
  get 'rooms/show'
  get 'rooms/new'
  post 'rooms/create'
  get 'rooms/edit'
  put 'rooms/update'
  delete 'rooms/destroy'

  get 'schedules/index'
  get 'schedules/show'
  get 'schedules/new'
  post 'schedules/create'
  get 'schedules/edit'
  put 'schedules/update'
  delete 'schedules/destroy'

  get 'medical_visits/index'
  get 'medical_visits/show'
  get 'medical_visits/new'
  post 'medical_visits/create'
  get 'medical_visits/edit'
  put 'medical_visits/update'
  delete 'medical_visits/destroy'
  get 'medical_visits/doctor_visits'
  get 'medical_visits/patient_change'

  get 'examinations/index'
  get 'examinations/show'
  get 'examinations/new'
  post 'examinations/create'
  get 'examinations/edit'
  put 'examinations/update'
  delete 'examinations/destroy'

  get 'medicines/show'
  get 'medicines/info'

  resources :medical_visits, only: [] do
    resources :visit_descriptions, :prescriptions
  end
  resources :examinations, only: [] do
    resources :examinationpositions
  end
  resources :users, only: [] do
    resources :chronic_diseases, :chronic_medicines, :alergic_medicines
  end

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords",  registrations: "users/registrations" }

  devise_scope :user do
    get "/login" => "users/sessions#new"
  end

  resources :admins, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :doctors, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :nurses, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :receptionists, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :patients, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :medical_visits, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

  resources :examinations, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :doctor, class_name: :User
  belongs_to :room
  validates :startTime, :endTime, :interval, :doctor, :room, presence: true
  validates :interval, inclusion: { in: [0, 1] }

	def self.validate_schedule(schedule)
  	true
  end

  def self.search(search)
  	if search
      all.joins(:doctor).joins(:room).where("users.name LIKE :query or users.surname LIKE :query or rooms.name LIKE :query or concat(users.name, ' ', users.surname) like :query or rooms.number like :query", query: "%#{search}%")
  	else
		all
		end
	end

  def self.doctor_visits(doctor, date)
    schedules = []
    where(doctor: doctor).each { |schedule|
      if schedule.interval == 0
        if schedule.startTime.to_date == date.to_date
          schedules.push schedule
        end
      else
        if (schedule.intervalEnd.nil? or schedule.intervalEnd.to_date >= date.to_date) and schedule.startTime.wday == date.wday
          schedules.push schedule
        end
      end
    }
    schedules
  end

  def self.visit_room(doctor, date)
    room_number = 0
    where(doctor: doctor).each { |schedule|
      if schedule.interval == 0
        if schedule.startTime.to_date == date.to_date
          room_number = schedule.room.number
        end
      else
        if (schedule.intervalEnd.nil? or schedule.intervalEnd.to_date >= date.to_date) and schedule.startTime.wday == date.wday
          room_number = schedule.room.number
        end
      end
    }
    room_number
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    if current_user.admin? or current_user.receptionist?
      @schedules = Schedule.joins(:doctor)
                           .search(params[:search])
                           .order('`' + (sort_column.empty? ? "id" : sort_column) + '` ' + sort_direction)
                           .paginate(:page => params[:page], :per_page => 20)
    elsif current_user.doctor?
      @schedules = Schedule.joins(:doctor)
                           .where(doctor: current_user)
                           .search(params[:search])
                           .order('`' + (sort_column.empty? ? "id" : sort_column) + '` ' + sort_direction)
                           .paginate(:page => params[:page], :per_page => 20)
    else
      @schedules = Schedule.joins(:doctor)
                           .search(params[:search])
                           .order('`' + (sort_column.empty? ? "id" : sort_column) + '` ' + sort_direction)
                           .paginate(:page => params[:page], :per_page => 20)
    end
  end

  def show
    begin
      @schedule = Schedule.find(params[:format])
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiego wpisu!"
      redirect_to schedules_index_path
    end
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.doctor = User.find(params[:schedule][:doctor])
    @schedule.room = Room.find(params[:schedule][:room])
    if not Schedule.validate_schedule(@schedule)
      flash[:alert] = "Nie możesz dodać takiej pozycji, ponieważ pokrywa się z inną"
      render :new
    elsif @schedule.save
      flash[:success] = "Pomyślnie dodano wpis do grafiku"
      redirect_to schedules_index_path
    else
      flash[:error] = "error"
      render :new
    end
  end

  def edit
    begin
      @schedule = Schedule.find(params[:format])
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiego wpisu!"
      redirect_to schedules_index_path
    end
  end

  def update
    begin
      @schedule = Schedule.find(params[:format])
      @schedule.doctor = User.find(params[:schedule][:doctor])
      @schedule.room = Room.find(params[:schedule][:room])
      if @schedule.update(schedule_params)
        flash[:success] = "Pomyślnie zaktualizowano wpis"
        redirect_to schedules_index_path
      else
        flash[:error] = "error"
        render :edit
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiego wpisu!"
      redirect_to schedules_index_path
    end
  end

  def destroy
    begin
      @schedule = Schedule.find(params[:format])
      @schedule.destroy
      flash[:success] = "Pomyślnie usunięto wpis"
      redirect_to schedules_index_path
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiego wpisu!"
      redirect_to schedules_index_path
    end
  end

  private
  def schedule_params
    params.require(:schedule).permit(:startTime, :endTime, :interval, :intervalEnd)
  end

  def sort_column
    Schedule.column_names.include?(params[:sort]) ? params[:sort] : (User.column_names.include?(params[:sort]) ? params[:sort] : "")
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_schedules.html.erb
<% i=((params[:page].present? ? params[:page].to_i : 1) - 1) * 20 %>
	<table class="table table-hover">
		<thead>
			<th>
				<%= link_to schedules_index_path(sortable("id")), class: "sortinglink" do %>
					Nr.<%= column_name("id") %>
				<% end %>
			</th>
			<th>
				<%= link_to schedules_index_path(sortable("surname")), class: "sortinglink" do %>
					Lekarz<%= column_name("surname") %>
				<% end %>
			</th>
			<th>
				<%= link_to schedules_index_path(sortable("room_id")), class: "sortinglink" do %>
					Gabinet<%= column_name("room_id") %>
				<% end %>
			</th>
			</th>
			<th>
				<%= link_to schedules_index_path(sortable("startTime")), class: "sortinglink" do %>
					Początek<%= column_name("startTime") %>
				<% end %>
			</th>
			</th>
			<th>
				<%= link_to schedules_index_path(sortable("endTime")), class: "sortinglink" do %>
					Koniec<%= column_name("endTime") %>
				<% end %>
			</th>
			<th>
				<%= link_to schedules_index_path(sortable("interval")), class: "sortinglink" do %>
					Czy cykliczne<%= column_name("interval") %>
				<% end %>
			</th>
			<th>Szczegóły</th>
			<% if current_user.admin? %>
				<th>Edytuj</th>
		 		<th>Usuń</th>
			<% end %>
	  </thead>
  	<tbody>
			<% @schedules.each do |f| %>
				<tr>
					<td><%= i+=1 %></td>
					<td><%= f.doctor.name %> <%= f.doctor.surname %></td>
					<td><%= f.room.name %> (<%= f.room.number %>)</td>
					<td><%= l(f.startTime, format: f.interval == 1 ? "%A %H:%M" : "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= l(f.endTime, format: f.interval == 1 ? "%A %H:%M" : "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= f.interval == 1 ? "Tak" : "Nie" %></td>
					<td><%= link_to "Szczegóły", schedules_show_path(f), :class => "btn btn-info"%></td>
					<% if current_user.admin? %>
						<td><%= link_to "Edytuj", schedules_edit_path(f), :class => "btn btn-primary"%></td>
	        	<td><%= link_to "Usuń", schedules_destroy_path(f), method: :delete, data: { confirm: 'Na pewno usunąć ten zesób?' }, :class => "btn btn-danger"%></td>
					<% end %>
				</tr>
			<% end %>
	  </tbody>
	</table>

<%= will_paginate @schedules, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>' %>

app/views/schedules/create.html.erb
<h1>Schedules#create</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/destroy.html.erb
<h1>Schedules#destroy</h1>
<p>Find me in app/views/schedules/destroy.html.erb</p>

app/views/schedules/edit.html.erb
<h1>Edycja pozycji grafiku</h1>
<% if @schedule.errors.any? %>
	<% @schedule.attributes.keys.each do |key| %>
		<% if @schedule.errors.full_messages_for(key.to_sym).length > 0  %>
			<%= @schedule.errors.full_messages_for(key.to_sym).first %> <br />
		<% end %>
	<% end %>
<% end %>

<div id="addscheduleform">

	<%= form_for @schedule, url: schedules_update_path(@schedule), :method => :put, html: { autocomplete: 'off' } do |f| %>
		<div class="form-group">
	    <%= f.label :Lekarz %><br />
	    <%= f.select(:doctor, User.where.not(doctor: nil).map { |e| ["#{e.name} #{e.surname}", e.id] }, {selected: @schedule.doctor.id}, {:class => "form-control"}) %>
	  </div>

		<div class="form-group">
	    <%= f.label :Gabinet %><br />
	    <%= f.select(:room, Room.all.map { |e| ["#{e.name} (#{e.number})", e.id] }, {selected: @schedule.room.id}, {:class => "form-control"}) %>
	  </div>

	  <div class="form-group">
		    <%= f.label "Czas rozpoczęcia" %>
		    	<div class='input-group date datetimepicker' id='datetimepicker1'>
		    		<%= f.text_field :startTime, class: "form-control", :value => @schedule.startTime.strftime("%d.%m.%Y %H:%M")%>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

		  <div class="form-group">
		    <%= f.label "Czas zakończenia" %>
		    	<div class='input-group date datetimepicker'>
		    		<%= f.text_field :endTime, class: "form-control", :value => @schedule.endTime.strftime("%d.%m.%Y %H:%M")%>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

		  <div class="form-group">
		  	<%= f.check_box :interval, id: "scheduleinterval" %>
		  	<%= f.label :interval, "Czy cykliczny"%>
		  </div>

		  <div class="form-group" id="scheduleintervalenddiv">
		    <%= f.label "Koniec wydarzenia cyklicznego" %>
		    	<div class='input-group date' id='datetimepicker'>
		    	<% if @schedule.intervalEnd %>
		    		<%= f.text_field :intervalEnd, class: "form-control",  :value => @schedule.intervalEnd.strftime("%d.%m.%Y")%>
		    	<% else %>
		    		<%= f.text_field :intervalEnd, class: "form-control"%>
		    	<% end %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

    <div class="actions">
	    <%= f.submit "Aktualizuj pozycję", class: "btn btn-primary" %>
	    <p><%= link_to "Powrót do grafiku", schedules_index_path, class: "linkto" %></p>
	  </div>
	<% end %>
</div>

app/views/schedules/index.html.erb
<h1>Grafik lekarzy</h1>

<% if current_user.admin? %>
	<div class="addlinkdiv">
		<p><%= link_to "Dodaj nowy wpis", schedules_new_path, class: "addlink"%></p>
	</div>
<% end %>

<div id="serarchdiv">
	<%= form_tag schedules_index_path, :method => :get, :class => "navbar-form navbar-left", :role => "search", :id => "schedules_search", :enforce_utf8 => false do %>
		<table class="table" id="searchtable">
			<thead>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Wyszukaj:</th>
			</thead>
			<tbody>
				<tr>
					<td>
					  <%= text_field_tag :search, params[:search], placeholder: "Wyszukaj", class: "form-control" %>
					</td>
		   	</tr>
			</tbody>
		</table>
	<% end %>
</div>

<div id="schedules">
	<%= render "schedules" %>
</div>

app/views/schedules/index.js.erb
$('#schedules').html('<%= escape_javascript(render("schedules")) %>');

app/views/schedules/new.html.erb
<h1>Dodawanie nowego wpisu do grafiku</h1>
<% if @schedule.errors.any? %>
	<% @schedule.attributes.keys.each do |key| %>
		<% if @schedule.errors.full_messages_for(key.to_sym).length > 0  %>
			<%= @schedule.errors.full_messages_for(key.to_sym).first %> <br />
		<% end %>
	<% end %>
<% end %>

<div id="addscheduleform">

	<%= form_for @schedule, url: schedules_create_path, :method => :post, html: { autocomplete: 'off' } do |f| %>
		<div class="form-group">
	    <%= f.label :Lekarz %><br />
	    <%= f.select(:doctor, User.where.not(doctor: nil).map { |e| ["#{e.name} #{e.surname}", e.id] }, {}, {:class => "form-control"}) %>
	  </div>

		<div class="form-group">
	    <%= f.label :Gabinet %><br />
	    <%= f.select(:room, Room.all.map { |e| ["#{e.name} (#{e.number})", e.id] }, {}, {:class => "form-control"}) %>
	  </div>

	  <div class="form-group">
		    <%= f.label "Czas rozpoczęcia" %>
		    	<div class='input-group datetimepicker' id='datetimepicker1'>
		    		<%= f.text_field :startTime, class: "form-control" %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

		  <div class="form-group">
		    <%= f.label "Czas zakończenia" %>
		    	<div class='input-group datetimepicker' id='datetimepicker1'>
		    		<%= f.text_field :endTime, class: "form-control" %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

		  <div class="form-group">
		  	<%= f.check_box :interval, id: "scheduleinterval" %>
		  	<%= f.label :interval, "Czy cykliczny"%>
		  </div>

		  <div class="form-group" id="scheduleintervalenddiv">
		    <%= f.label "Koniec wydarzenia cyklicznego" %>
		    	<div class='input-group date' id="datetimepicker">
		    		<%= f.text_field :intervalEnd, class: "form-control" %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

    <div class="actions">
	    <%= f.submit "Dodaj wpis do grafiku", class: "btn btn-primary" %>
	    <p><%= link_to "Powrót do grafiku", schedules_index_path, class: "linkto" %></p>
	  </div>
	<% end %>
</div>

app/views/schedules/show.html.erb
<h1>Pozycja grafiku</h1>

<div id="scheduleshowdiv">
	<table class="table table-hover">
	    <tr>
	    	<td id="firstrow">Lekarz:</td>
      	<td id="firstrow"><%= @schedule.doctor.name %> <%= @schedule.doctor.surname %></td>
	    </tr>
	    <tr>
	    	<td>Gabinet:</td>
	      <td><%= @schedule.room.name %> (<%= @schedule.room.number %>)</td>
	    </tr>
	    <tr>
	    	<td>Czas rozpoczęcia:</td>
	      <td><%= l(@schedule.startTime, format: @schedule.interval == 1 ? "%A %H:%M" : "%d.%m.%Y %H:%M").humanize %></td>
	    </tr>
	    <tr>
	    	<td>Czas zakończenia:</td>
	      <td><%= l(@schedule.endTime, format: @schedule.interval == 1 ? "%A %H:%M" : "%d.%m.%Y %H:%M").humanize %></td>
	    </tr>
	    <tr>
	    	<td>Czy cykliczne:</td>
	      <td><%= @schedule.interval == 1 ? "Tak" : "Nie" %> </td>
	    </tr>
	    <% if @schedule.interval == 1 %>
		    <tr>
		    	<td>Czas zakończenia interwału:</td>
		      <td><%= @schedule.intervalEnd.strftime("%d.%m.%Y %H:%M") if @schedule.intervalEnd %> </td>
		    </tr>
	    <% end %>
	</table>
</div>

<p><%= link_to "Powrót do grafiku", schedules_index_path, class: "linkto" %></p>

app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>