config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  get 'admins/index'
  get 'admins/show'
  get 'admins/new'
  post 'admins/create'
  get 'admins/edit'
  put 'admins/update'
  delete 'admins/destroy'

  get 'doctors/index'
  get 'doctors/show'
  get 'doctors/new'
  post 'doctors/create'
  get 'doctors/edit'
  put 'doctors/update'
  delete 'doctors/destroy'

  get 'nurses/index'
  get 'nurses/show'
  get 'nurses/new'
  post 'nurses/create'
  get 'nurses/edit'
  put 'nurses/update'
  delete 'nurses/destroy'

  get 'receptionists/index'
  get 'receptionists/show'
  get 'receptionists/new'
  post 'receptionists/create'
  get 'receptionists/edit'
  put 'receptionists/update'
  delete 'receptionists/destroy'

  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  post 'patients/create'
  get 'patients/edit'
  put 'patients/update'
  delete 'patients/destroy'

  get 'rooms/index'
  get 'rooms/show'
  get 'rooms/new'
  post 'rooms/create'
  get 'rooms/edit'
  put 'rooms/update'
  delete 'rooms/destroy'

  get 'schedules/index'
  get 'schedules/show'
  get 'schedules/new'
  post 'schedules/create'
  get 'schedules/edit'
  put 'schedules/update'
  delete 'schedules/destroy'

  get 'medical_visits/index'
  get 'medical_visits/show'
  get 'medical_visits/new'
  post 'medical_visits/create'
  get 'medical_visits/edit'
  put 'medical_visits/update'
  delete 'medical_visits/destroy'
  get 'medical_visits/doctor_visits'
  get 'medical_visits/patient_change'

  get 'examinations/index'
  get 'examinations/show'
  get 'examinations/new'
  post 'examinations/create'
  get 'examinations/edit'
  put 'examinations/update'
  delete 'examinations/destroy'

  get 'medicines/show'
  get 'medicines/info'

  resources :medical_visits, only: [] do
    resources :visit_descriptions, :prescriptions
  end
  resources :examinations, only: [] do
    resources :examinationpositions
  end
  resources :users, only: [] do
    resources :chronic_diseases, :chronic_medicines, :alergic_medicines
  end

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords",  registrations: "users/registrations" }

  devise_scope :user do
    get "/login" => "users/sessions#new"
  end

  resources :admins, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :doctors, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :nurses, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :receptionists, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :patients, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :medical_visits, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

  resources :examinations, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

end

app/models/medical_visit.rb
class MedicalVisit < ActiveRecord::Base
  belongs_to :visit_description
  belongs_to :doctor, class_name: :User
  belongs_to :patient, class_name: :User
  has_many :prescriptions

  validates :doctor, :patient, :startTime, :patient_id, presence: true
end

app/controllers/medical_visits_controller.rb
class MedicalVisitsController < ApplicationController
  helper_method :sort_column, :sort_direction
  autocomplete :patient, :name, :display_value => :patient_name, :extra_data => [:surname, :pesel], :full => true

  def index
    if current_user.doctor? and params[:format]
      @medical_visits = MedicalVisit.joins(:doctor)
                                    .where(patient: User.find(params[:format]))
                                    .where(ended: 1)
                                    .order('`' + (sort_column.empty? ? "startTime" : sort_column) + '` ' + sort_direction)
                                    .paginate(:page => params[:page1], :per_page => 20)
    elsif current_user.doctor?
      date = params[:date].present? ? Time.parse(params[:date]) : Time.now
      @medical_visits = MedicalVisit.joins(:patient)
                                    .where(doctor: current_user)
                                    .where("date(startTime) = :date",  date: "#{date.to_date}")
                                    .order('`' + (sort_column.empty? ? "startTime" : sort_column) + '` ' + sort_direction)
                                    .paginate(:page => params[:page], :per_page => 20)
    elsif current_user.patient?
      @medical_visits = MedicalVisit.joins(:doctor)
                                    .where(patient: current_user)
                                    .where("date(startTime) >= :date",  date: "#{Time.now.to_date}")
                                    .order('`' + (sort_column.empty? ? "startTime" : sort_column) + '` ' + sort_direction)
                                    .paginate(:page => params[:page1], :per_page => 10)
      @ended_visits = MedicalVisit.joins(:doctor)
                                  .where(patient: current_user)
                                  .where("date(startTime) < :date",  date: "#{Time.now.to_date}")
                                  .order('`' + (sort_column.empty? ? "startTime" : sort_column) + '` ' + sort_direction)
                                  .paginate(:page => params[:page2], :per_page => 10)
    else
      @medical_visits = MedicalVisit.where("date(startTime) >= :date",  date: "#{Time.now.to_date}")
                                    .order('`' + (sort_column.empty? ? "startTime" : sort_column) + '` ' + sort_direction)
                                    .paginate(:page => params[:page], :per_page => 20)
    end
  end

  def show
    begin
      @medical_visit = MedicalVisit.find(params[:format])
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej wizyty!"
      redirect_to medical_visits_index_path
    end
  end

  def new
    @medical_visit = MedicalVisit.new
    if current_user.patient?
      @doctor = current_user.patient.maindoctor.user
    else
      @doctor = User.where.not(doctor: nil).first
    end
    @date = Time.now
    @visits = visits_to_display(@doctor, @date)
  end

  def create
    @medical_visit = MedicalVisit.new(medical_visit_params)
    @medical_visit.doctor = doctor_param
    @medical_visit.endTime = @medical_visit.startTime + 15*60 if @medical_visit.startTime
    if current_user.patient?
      @medical_visit.patient = current_user
    else
      @medical_visit.patient = patient_param
    end
    unless validate @medical_visit and @medical_visit.startTime > Time.now
      @doctor = doctor_param
      @date = @medical_visit.startTime ? @medical_visit.startTime : DateTime.now
      @visits = visits_to_display(@doctor, @date)
      flash[:alert] = "Nie możesz zarejestrować wizyty w tym terminie"
      render :new
    else
      if @medical_visit.save
        flash[:notice] = "Udało się pomyślnie zarejestrować nową wizytę"
        redirect_to medical_visits_index_path
      else
        @doctor = doctor_param
        @date = @medical_visit.startTime
        @visits = visits_to_display(@doctor, @date)
        flash[:error] = "error"
        render :new
      end
    end
  end

  def edit
    begin
      @medical_visit = MedicalVisit.find(params[:format])
      if current_user.patient?
        if @medical_visit.patient != current_user or @medical_visit.startTime < Time.now
          flash[:alert] = "Nie możesz edytować tej wizyty!"
          redirect_to medical_visits_index_path
        else
          @doctor = @medical_visit.doctor
          @date = @medical_visit.startTime
          @visits = visits_to_display(@doctor, @date)
          render :edit
        end
      else
        if @medical_visit.startTime < Time.now
          flash[:alert] = "Nie możesz edytować tej wizyty!"
          redirect_to medical_visits_index_path
        else
          @doctor = @medical_visit.doctor
          @date = @medical_visit.startTime
          @visits = visits_to_display(@doctor, @date)
          render :edit
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej wizyty!"
      redirect_to medical_visits_index_path
    end
  end

  def update
    begin
      @medical_visit = MedicalVisit.find(params[:format])
      @medical_visit.startTime = Time.parse(params.require(:medical_visit).permit(:startTime).to_s)
      @medical_visit.doctor = doctor_param
      @medical_visit.endTime = @medical_visit.startTime + 15*60 if @medical_visit.startTime
      if current_user.patient?
        @medical_visit.patient = current_user
      else
        @medical_visit.patient = patient_param
      end
      unless validate @medical_visit or @medical_visit.startTime > Time.now
        @doctor = doctor_param
        @date = @medical_visit.startTime ? @medical_visit.startTime : DateTime.now
        @visits = visits_to_display(@doctor, @date)
        flash[:alert] = "Nie możesz zarejestrować wizyty w tym terminie"
        render :edit
      else
        if @medical_visit.save
          flash[:notice] = "Pomyślnie zmodyfikowano wizytę"
          redirect_to medical_visits_index_path
        else
          @doctor = doctor_param
          @date = @medical_visit.startTime
          @visits = visits_to_display(@doctor, @date)
          flash[:error] = "error"
          render :edit
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej wizyty!"
      redirect_to medical_visits_index_path
    end
  end

  def destroy
    begin
      @medical_visit = MedicalVisit.find(params[:format])
      if @medical_visit.startTime > Time.now and (current_user.receptionist? or current_user = @medical_visit.patient) and @medical_visit.destroy
        flash[:notice] = "Pomyslnie wizytę"
        redirect_to medical_visits_index_path
      else
        flash[:alert] = "Nie możesz usunąć tej wizyty"
        redirect_to medical_visits_index_path
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej wizyty!"
      redirect_to medical_visits_index_path
    end
  end

  def doctor_visits
    @doctor = User.find(params.require(:medical_visit)[:doctor])
    @date = params.require(:medical_visit)[:startTime].empty? ? DateTime.now : DateTime.parse(params.require(:medical_visit)[:startTime])
    @visits = visits_to_display(@doctor, @date)
  end

  def patient_change
    @patient = User.find(params.require(:post)[:patient_id]) if params.require(:post)[:patient_id].present?
    @doctor = !@patient.nil? ? @patient.patient.maindoctor.user :  User.find(params.require(:medical_visit)[:doctor])
    @date = params.require(:medical_visit)[:startTime].empty? ? DateTime.now : DateTime.parse(params.require(:medical_visit)[:startTime])
    @visits = visits_to_display(@doctor, @date)
  end

  def get_autocomplete_items(parameters)
    User.where("patient_id is not null and isactive = 1 and (name like :query or surname like :query or pesel like :query or CONCAT_WS(' ', name, surname, pesel) like :query)", query: "%#{parameters[:term]}%")
  end

  private
  def medical_visit_params
    params.require(:medical_visit).permit(:startTime)
  end

  def doctor_param
    User.find(params.require(:medical_visit)[:doctor]) unless params.require(:medical_visit)[:doctor].empty?
  end

  def patient_param
    User.find(params.require(:post)[:patient_id]) unless params.require(:post)[:patient_id].empty?
  end

  def validate medical_visit
    enable = false
    unless medical_visit.startTime
      enable = false
    else
      schedules = Schedule.where(doctor: doctor_param)
      schedules.each { |schedule|
        if schedule.interval == 0
          enable = (enable or
                   (schedule.startTime <= medical_visit.startTime and
                   schedule.endTime >= (medical_visit.startTime + 15*60) and
                   MedicalVisit.where(startTime: medical_visit.startTime).where(doctor: medical_visit.doctor).count() == 0))
        else
          enable = (enable or
                   (schedule.startTime.wday == medical_visit.startTime.wday and
                   schedule.startTime.utc.strftime( "%H%M" ) <= medical_visit.startTime.utc.strftime( "%H%M" ) and
                   schedule.endTime.utc.strftime( "%H%M" ) >= (medical_visit.startTime + 15*60).utc.strftime( "%H%M" ) and
                   MedicalVisit.where(startTime: medical_visit.startTime).where(doctor: medical_visit.doctor).count() == 0))
        end
      }
    end
    enable
  end

  Visit = Struct.new(:start, :end, :status)

  def visits_to_display(doctor, date)
    visits = []
    Schedule.doctor_visits(doctor, date).each { |schedule|
      if schedule.startTime.to_date == date.to_date
        startTime = schedule.startTime
        puts date.to_date
        endTime = schedule.endTime
      else
        startTime = Time.parse(date.strftime("%Y-%m-%d").to_s + " " +schedule.startTime.strftime("%H:%M").to_s)
        endTime = Time.parse(date.strftime("%Y-%m-%d").to_s + " " +schedule.endTime.to_time.strftime("%H:%M").to_s)
      end
      while startTime < endTime
        result = MedicalVisit.where(doctor: doctor).where(startTime: startTime)
        v = Visit.new
        v.start = startTime

app/helpers/medical_visits_helper.rb
module MedicalVisitsHelper
	def get_patient_id(patient)
    User.where("concat(name, surname, ' (', pesel, ')') like ?", "%#{patient.name}%").pluck(:id).first if patient
  end
end

app/views/medical_visits/_doctorindexvisits.html.erb
<div id="dateserarchdiv">
	<%= form_tag medical_visits_index_path, :method => :get, :class => "navbar-form navbar-left", :role => "search", :id => "medical_visits_search_date", :enforce_utf8 => false do %>
		<table class="table" id="searchtable">
			<thead>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Wybierz datę:</th>
			</thead>
			<tbody>
				<tr>
					<td>
		    		<div class='input-group date datesearch' id='datetimesearchpicker'>
		    			<%= text_field_tag :date, params[:date], placeholder: "Wyszukaj", class: "form-control" %>
		    			<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
		           </span>
		        </div>
					</td>
		   	</tr>
			</tbody>
		</table>
	<% end %>
</div>

<% i=((params[:page].present? ? params[:page].to_i : 1) - 1) * 20 %>
	<table class="table table-hover">
		<thead>
			<th>
				<%= link_to medical_visits_index_path(sortable("id")), class: "sortinglink" do %>
					Nr.<%= column_name("id") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("startTime")), class: "sortinglink" do %>
					Początek<%= column_name("startTime") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("endTime")), class: "sortinglink" do %>
					Koniec<%= column_name("endTime") %>
				<% end %>
			</th>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("surname")), class: "sortinglink" do %>
					Pacjent<%= column_name("surname") %>
				<% end %>
			</th>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("room")), class: "sortinglink" do %>
					Gabinet<%= column_name("room") %>
				<% end %>
			</th>
			<th>Szczegóły</th>
			<th>Edytuj</th>
	  </thead>
  	<tbody>
			<% @medical_visits.each do |f| %>
				<tr>
					<td><%= i+=1 %></td>
					<td><%= l(f.startTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= l(f.endTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= f.patient.name %> <%= f.patient.surname %></td>
					<td><%= Schedule.visit_room(f.doctor, f.startTime) %></td>
					<td><%= link_to "Szczegóły", medical_visits_show_path(f), :class => "btn btn-info"%></td>
					<% if f.startTime.to_date == Time.now.to_date %>
			    	<td><%= link_to "Edytuj", new_medical_visit_visit_description_path(f), :class => "btn btn-primary"%></td>
					<% end %>
				</tr>
			<% end %>
	  </tbody>
	</table>

<%= will_paginate @medical_visits, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>' %>

app/views/medical_visits/_patientform.html.erb
<div id="medicalvisitform">

	<%= form_for @medical_visit, url: ((params[:action] == 'new' or params[:action] == 'create') ? medical_visits_create_path : medical_visits_update_path(@medical_visit)), :method => (params[:action] == 'new' or params[:action] == 'create' ? :post : :put), html: { autocomplete: 'off' } do |f| %>
		<div class="form-group">
	    <%= f.label :Lekarz %><br />
	    <%= f.select(:doctor, User.where.not(doctor: nil).where(isactive: true).map { |e| ["#{e.name} #{e.surname}", e.id] }, {selected: @medical_visit.doctor ? @medical_visit.doctor.id :  current_user.patient.maindoctor.user.id}, {:class => "form-control"}) %>
	  </div>

	  <div class="form-group">
		    <%= f.label "Czas rozpoczęcia" %>
		    	<div class='input-group date datetimepickerdatetime' id='datetimepicker1'>
		    		<% if @medical_visit.startTime.nil? %>
			    		<%= f.text_field :startTime, class: "form-control" %>
			    	<% else %>
			    		<%= f.text_field :startTime, class: "form-control", value: l(@medical_visit.startTime, format: "%d.%m.%Y %H:%M").humanize %>
			    	<% end %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

    <div class="actions">
	    <%= f.submit "Zapisz wizytę", class: "btn btn-primary" %>
	    <p><%= link_to "Powrót do wizyt", medical_visits_index_path, class: "linkto" %></p>
	  </div>
	<% end %>
</div>
<div id="medicalvisitformdoctors">
	<%= render 'doctorvisits' %>
</div>

app/views/medical_visits/_patientvisits.html.erb
<h3>Zaplanowane wizyty</h3>
<% i=((params[:page1].present? ? params[:page1].to_i : 1) - 1) * 10 %>
	<table class="table table-hover">
		<thead>
			<th>
				<%= link_to medical_visits_index_path(sortable("id")), class: "sortinglink" do %>
					Nr.<%= column_name("id") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("startTime")), class: "sortinglink" do %>
					Początek<%= column_name("startTime") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("endTime")), class: "sortinglink" do %>
					Koniec<%= column_name("endTime") %>
				<% end %>
			</th>
			</th>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("surname")), class: "sortinglink" do %>
					Lekarz<%= column_name("surname") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("room")), class: "sortinglink" do %>
					Gabinet<%= column_name("room") %>
				<% end %>
			</th>
			<th>Szczegóły</th>
			<th>Edytuj</th>
	  </thead>
  	<tbody>
			<% @medical_visits.each do |f| %>
				<tr>
					<td><%= i+=1 %></td>
					<td><%= l(f.startTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= l(f.endTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= f.doctor.name %> <%= f.doctor.surname %></td>
					<td><%= Schedule.visit_room(f.doctor, f.startTime) %></td>
					<td><%= link_to "Szczegóły", medical_visits_show_path(f), :class => "btn btn-info"%></td>
			    <td><%= link_to "Edytuj", medical_visits_edit_path(f), :class => "btn btn-primary"%></td>
				</tr>
			<% end %>
	  </tbody>
	</table>

<%= will_paginate @medical_visits, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>', param_name: 'page1' %>

<h3>Odbyte wizyty</h3>
<% i=((params[:page2].present? ? params[:page2].to_i : 1) - 1) * 20 %>
	<table class="table table-hover">
		<thead>
			<th>
				<%= link_to medical_visits_index_path(sortable("id")), class: "sortinglink" do %>
					Nr.<%= column_name("id") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("startTime")), class: "sortinglink" do %>
					Początek<%= column_name("startTime") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("endTime")), class: "sortinglink" do %>
					Koniec<%= column_name("endTime") %>
				<% end %>
			</th>
			</th>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("surname")), class: "sortinglink" do %>
					Lekarz<%= column_name("surname") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("room")), class: "sortinglink" do %>
					Gabinet<%= column_name("room") %>
				<% end %>
			</th>
			<th>Szczegóły</th>
	  </thead>
  	<tbody>
			<% @ended_visits.each do |f| %>
				<tr>
					<td><%= i+=1 %></td>
					<td><%= l(f.startTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= l(f.endTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= f.doctor.name %> <%= f.doctor.surname %></td>
					<td><%= Schedule.visit_room(f.doctor, f.startTime) %></td>
					<td><%= link_to "Szczegóły", medical_visits_show_path(f), :class => "btn btn-info"%></td>
				</tr>
			<% end %>
	  </tbody>
	</table>

<%= will_paginate @ended_visits, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>', param_name: 'page2' %>

app/views/medical_visits/_receptionistform.html.erb
<div id="medicalvisitform">

	<%= form_for @medical_visit, url: ((params[:action] == 'new' or params[:action] == 'create') ? medical_visits_create_path : medical_visits_update_path(@medical_visit)), :method => (params[:action] == 'new' or params[:action] == 'create' ? :post : :put), html: { autocomplete: 'off' } do |f| %>
		<div class="form-group">
	    <%= f.label :Lekarz %><br />
	    <%= f.select(:doctor, User.where.not(doctor: nil).where(isactive: true).map { |e| ["#{e.name} #{e.surname}", e.id] }, {selected: @medical_visit.doctor ? @medical_visit.doctor.id :  User.where.not(doctor: nil).first.id}, {:class => "form-control"}) %>
	  </div>

		<div class="form-group">
	    <%= f.label :Pacient %><br />
	  	<%= f.autocomplete_field :patient ,autocomplete_patient_name_medical_visits_path,'data-auto-focus' => true, class: "form-control", :id_element => '#post_patient_id', "data-auto-label" => "Sorry, nothing found.", :append_to => "#autocompleteresult"%>
			<%= hidden_field(:post, :patient_id, :value => get_patient_id(@medical_visit.patient))%>
	  	<div id="autocompleteresult">
	  	</div>
	  </div>

	  <div class="form-group">
		    <%= f.label "Czas rozpoczęcia" %>
		    	<div class='input-group date datetimepickerdatetime' id='datetimepicker1'>
		    	<% if @medical_visit.startTime.nil? %>
		    		<%= f.text_field :startTime, class: "form-control" %>
		    	<% else %>
		    		<%= f.text_field :startTime, class: "form-control", value: l(@medical_visit.startTime, format: "%d.%m.%Y %H:%M").humanize %>
		    	<% end %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>

    <div class="actions">
	    <%= f.submit "Zapisz wizytę", class: "btn btn-primary" %>
	    <p><%= link_to "Powrót do wizyt", medical_visits_index_path, class: "linkto" %></p>
	  </div>
	<% end %>
</div>
<div id="medicalvisitformdoctors">
	<%= render 'doctorvisits' %>
</div>

app/views/medical_visits/_receptionistvisits.html.erb
<% i=((params[:page].present? ? params[:page].to_i : 1) - 1) * 20 %>
	<table class="table table-hover">
		<thead>
			<th>
				<%= link_to medical_visits_index_path(sortable("id")), class: "sortinglink" do %>
					Nr.<%= column_name("id") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("startTime")), class: "sortinglink" do %>
					Początek<%= column_name("startTime") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("endTime")), class: "sortinglink" do %>
					Koniec<%= column_name("endTime") %>
				<% end %>
			</th>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("patient_id")), class: "sortinglink" do %>
					Pacjent<%= column_name("patient_id") %>
				<% end %>
			</th>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("doctor_id")), class: "sortinglink" do %>
					Lekarz<%= column_name("doctor_id") %>
				<% end %>
			</th>
			<th>
				<%= link_to medical_visits_index_path(sortable("room")), class: "sortinglink" do %>
					Gabinet<%= column_name("room") %>
				<% end %>
			</th>
			<th>Szczegóły</th>
			<th>Edytuj</th>
		 	<th>Usuń</th>
	  </thead>
  	<tbody>
			<% @medical_visits.each do |f| %>
				<tr>
					<td><%= i+=1 %></td>
					<td><%= l(f.startTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= l(f.endTime, format: "%d.%m.%Y %H:%M").humanize %></td>
					<td><%= f.patient.name %> <%= f.patient.surname %></td>
					<td><%= f.doctor.name %> <%= f.doctor.surname %></td>
					<td><%= Schedule.visit_room(f.doctor, f.startTime) %></td>
					<td><%= link_to "Szczegóły", medical_visits_show_path(f), :class => "btn btn-info"%></td>
			    <td><%= link_to "Edytuj", medical_visits_edit_path(f), :class => "btn btn-primary"%></td>
	        <td><%= link_to "Usuń", medical_visits_destroy_path(f), method: :delete, data: { confirm: 'Na pewno usunąć ten zesób?' }, :class => "btn btn-danger"%></td>
				</tr>
			<% end %>
	  </tbody>
	</table>

<%= will_paginate @medical_visits, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>' %>

app/views/medical_visits/create.html.erb
<h1>MedicalVisits#create</h1>
<p>Find me in app/views/medical_visits/create.html.erb</p>

app/views/medical_visits/doctor_visits.js.erb
$('#medicalvisitformdoctors').html('<%= escape_javascript(render("doctorvisits")) %>');