config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  get 'admins/index'
  get 'admins/show'
  get 'admins/new'
  post 'admins/create'
  get 'admins/edit'
  put 'admins/update'
  delete 'admins/destroy'

  get 'doctors/index'
  get 'doctors/show'
  get 'doctors/new'
  post 'doctors/create'
  get 'doctors/edit'
  put 'doctors/update'
  delete 'doctors/destroy'

  get 'nurses/index'
  get 'nurses/show'
  get 'nurses/new'
  post 'nurses/create'
  get 'nurses/edit'
  put 'nurses/update'
  delete 'nurses/destroy'

  get 'receptionists/index'
  get 'receptionists/show'
  get 'receptionists/new'
  post 'receptionists/create'
  get 'receptionists/edit'
  put 'receptionists/update'
  delete 'receptionists/destroy'

  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  post 'patients/create'
  get 'patients/edit'
  put 'patients/update'
  delete 'patients/destroy'

  get 'rooms/index'
  get 'rooms/show'
  get 'rooms/new'
  post 'rooms/create'
  get 'rooms/edit'
  put 'rooms/update'
  delete 'rooms/destroy'

  get 'schedules/index'
  get 'schedules/show'
  get 'schedules/new'
  post 'schedules/create'
  get 'schedules/edit'
  put 'schedules/update'
  delete 'schedules/destroy'

  get 'medical_visits/index'
  get 'medical_visits/show'
  get 'medical_visits/new'
  post 'medical_visits/create'
  get 'medical_visits/edit'
  put 'medical_visits/update'
  delete 'medical_visits/destroy'
  get 'medical_visits/doctor_visits'
  get 'medical_visits/patient_change'

  get 'examinations/index'
  get 'examinations/show'
  get 'examinations/new'
  post 'examinations/create'
  get 'examinations/edit'
  put 'examinations/update'
  delete 'examinations/destroy'

  get 'medicines/show'
  get 'medicines/info'

  resources :medical_visits, only: [] do
    resources :visit_descriptions, :prescriptions
  end
  resources :examinations, only: [] do
    resources :examinationpositions
  end
  resources :users, only: [] do
    resources :chronic_diseases, :chronic_medicines, :alergic_medicines
  end

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords",  registrations: "users/registrations" }

  devise_scope :user do
    get "/login" => "users/sessions#new"
  end

  resources :admins, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :doctors, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :nurses, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :receptionists, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :patients, only: [:autocomplete_city_name] do
    get :autocomplete_city_name, :on => :collection
  end

  resources :medical_visits, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

  resources :examinations, only: [:autocomplete_patient_name] do
    get :autocomplete_patient_name, :on => :collection
  end

end

app/models/receptionist.rb
class Receptionist < ActiveRecord::Base
	has_one :user

  validates :position, :employmentDate, presence: true
end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController
  helper_method :sort_column, :sort_direction
  autocomplete :city, :name, :display_value => :full_name, :extra_data => [:city_code], :full => true

  def index
    @users = User.joins(:receptionist)
                 .search(params[:search])
                 .order((sort_column.empty? ? "id" : sort_column) + ' ' + sort_direction)
                 .paginate(:page => params[:page], :per_page => 20)
  end

  def show
    begin
      @user = User.find(params[:format])
      if !@user.receptionist?
        flash[:alert] = "Wybrany użytkownik nie jest recepcjonistką"
        redirect_to receptionists_index_path
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej recepcjonistki!"
      redirect_to receptionists_index_path
    end
  end

  def new
    @user = User.new
    @user.receptionist = Receptionist.new
  end

  def create
    @user = User.new(user_params)
    @user.isactive = true
    @user.password = generate_password
    @user.city = user_city
    receptionist = Receptionist.new(receptionist_params)
    @user.receptionist = receptionist
    @user.sex = params[:sex]
    if @user.save
      UserNotifier.receptionist_registration(@user).deliver_now
      flash[:notice] = "Udało się pomyślnie zarejstrować nową recepcjonistkę"
      redirect_to receptionists_index_path
    else
      flash[:error] = "error"
      render :new
    end
  end

  def edit
    begin
      @user = User.find(params[:format])
      if !@user.receptionist?
        flash[:alert] = "Wybrany użytkownik nie jest recepcjonistką"
        redirect_to receptionists_index_path
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej recepcjonistki!"
      redirect_to receptionists_index_path
    end
  end

  def update
    begin
      @user = User.find(params[:format])
      if !@user.receptionist?
        flash[:alert] = "Wybrany użytkownik nie jest recepcjonistką"
        redirect_to receptionists_index_path
      end
      @receptionist = @user.receptionist
      @user.sex = params[:sex]
      @user.city = user_city
      @receptionist.update(receptionist_params)
      if @user.update(user_params)
        flash[:notice] = "Udało się pomyślnie edytować recepcjonistkę."
        redirect_to receptionists_index_path
      else
        flash[:error] = "error"
        render :edit
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej recepcjonistki!"
      redirect_to receptionists_index_path
    end
  end

  def destroy
    begin
      @user = User.find(params[:format])
      if !@user.receptionist?
        flash[:alert] = "Wybrany użytkownik nie jest recepcjonistką"
        redirect_to receptionists_index_path
      end
      @user.isactive = false
      if @user.save
        flash[:notice] = "Udało się pomyślnie usunąć recepcjonistkę."
        redirect_to receptionists_index_path
      else
        flash[:error] = "Błąd podczas usuania recepcjonistki"
        redirect_to receptionists_index_path
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie ma takiej recepcjonistki!"
      redirect_to receptionists_index_path
    end
  end

  def get_autocomplete_items(parameters)
    City.where("name like ? or city_code like ? or concat(name, ' ', city_code) like ? or concat(name, ' (', city_code, ')') like ?",
      "%#{parameters[:term]}%", "%#{parameters[:term]}%", "%#{parameters[:term]}%", "%#{parameters[:term]}%").limit(1000)
  end

  private
  def receptionist_params
    params.require(:user).require(:receptionist_attributes).permit(:position, :employmentDate, :dismissalDate)
  end

  def user_params
    params.require(:user).permit(:name, :surname, :login, :email, :street, :address, :pesel, :phone, :sex)
  end

  def user_city
    City.find(params.require(:post)[:city_id]) unless params.require(:post)[:city_id].empty?
  end

  def generate_password
    password = 8.times.map{([*('a'..'z')]).sample}.join
    first = rand(8)
    secound = rand(8)
    while first == secound do
      secound = rand(8)
    end
    password[first] = password[first].upcase
    password[secound] = rand(10).to_s
    password
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : (Receptionist.column_names.include?(params[:sort]) ? params[:sort] : "")
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/views/receptionists/_receptionists.html.erb
<% i=((params[:page].present? ? params[:page].to_i : 1) - 1) * 20 %>
	<table class="table table-hover">
		<thead>
		<th>
			<%= link_to receptionists_index_path(sortable("id")), class: "sortinglink" do %>
				Nr.<%= column_name("id") %>
			<% end %>
		</th>
		<th>
			<%= link_to receptionists_index_path(sortable("surname")), class: "sortinglink" do %>
				Imię i nazwisko<%= column_name("surname") %>
			<% end %>
		</th>
		<th>
			<%= link_to receptionists_index_path(sortable("login")), class: "sortinglink" do %>
				Login<%= column_name("login") %>
			<% end %>
		</th>
		<th>
			<%= link_to receptionists_index_path(sortable("isactive")), class: "sortinglink" do %>
				Status<%= column_name("isactive") %>
			<% end %>
		</th>
		<th>
			<%= link_to receptionists_index_path(sortable("position")), class: "sortinglink" do %>
				Stanowisko<%= column_name("position") %>
			<% end %>
		</th>
		<th>Szczegóły</th>
		<th>Edytuj</th>
	 	<th>Usuń</th>
	  	</thead>
	  	<tbody>
		<% @users.each do |f| %>
			<tr>
				<td><%= i+=1 %></td>
				<td><%= f.name %> <%= f.surname %></td>
				<td><%= f.login %></td>
				<td><%= f.isactive ? "Aktywny" : "Usunięty" %></td>
				<td><%= f.receptionist.position %></td>
				<td><%= link_to "Szczegóły", receptionists_show_path(f), :class => "btn btn-info"%></td>
        <td><%= link_to "Edytuj", receptionists_edit_path(f), :class => "btn btn-primary"%></td>
        <td><%= link_to "Usuń", receptionists_destroy_path(f), method: :delete, data: { confirm: 'Na pewno usunąć ten zesób?' }, :class => "btn btn-danger"%></td>
			</tr>
		<% end %>
	  </tbody>
	</table>

<%= will_paginate @users, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>' %>

app/views/receptionists/edit.html.erb
<h1>Edycja recepcjonistki <%= @user.name %> <%= @user.surname %></h1>
<% if @user.errors.any? %>
	<% @user.attributes.keys.each do |key| %>
		<% if @user.errors.full_messages_for(key.to_sym).length > 0  %>
			<%= @user.errors.full_messages_for(key.to_sym).first %> <br />
		<% end %>
	<% end %>
<% end %>
<% if @user.receptionist.errors.full_messages.any? %>
	<% @user.receptionist.attributes.keys.each do |key| %>
		<% if @user.receptionist.errors.full_messages_for(key.to_sym).length > 0  %>
			<%= @user.receptionist.errors.full_messages_for(key.to_sym).first %> <br />
		<% end %>
	<% end %>
<% end %>

<div id="receptionistregistrationform">

	<%= form_for @user, url: receptionists_update_path(@user), :method => :put, html: { autocomplete: 'off' } do |f| %>
		<div class="form-group">
	    <%= f.label :Imię %><br />
	    <%= f.text_field :name, autofocus: true, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Nazwisko %><br />
	    <%= f.text_field :surname, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Płeć %><br />
	    <%= select_tag :sex, options_for_select([['Kobieta', 0], ['Mężczyzna', 1]], @user.sex),  class: "form-control" %>
	  </div>


	  <div class="form-group">
	    <%= f.label :Login %><br />
	    <%= f.text_field :login, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label 'E-mail' %><br />
	    <%= f.email_field :email, class: "form-control" %>
	  </div>

		<div class="form-group">
	    <%= f.label :Miasto %><br />
	  	<%= f.autocomplete_field :city ,autocomplete_city_name_admins_path,'data-auto-focus' => true, class: "form-control", :id_element => '#post_city_id', "data-auto-label" => "Sorry, nothing found.", :append_to => "#autocompleteresult"%>
	  	<%= hidden_field(:post, :city_id, :value => get_city_id(@user.city))%>
	  	<div id="autocompleteresult">
	  	</div>
	  </div>

	  <div class="form-group">
	    <%= f.label :Ulica %><br />
	    <%= f.text_field :street, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label 'Nr domu i mieszkania' %><br />
	    <%= f.text_field :address, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Pesel %><br />
	    <%= f.text_field :pesel, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Telefon %><br />
	    <%= f.text_field :phone, class: "form-control" %>
	  </div>

		<%= f.fields_for :receptionist do |f1| %>
		  <div class="form-group">
		    <%= f1.label :Stanowisko %>
		    <%= f1.text_field :position, class: "form-control" %>
		  </div>

		  <div class="form-group">
		    <%= f1.label "Data zatrudnienia" %>
		    	<div class='input-group date' id='datetimepicker'>
		    		<% if @user.receptionist.employmentDate.nil? %>
			    		<%= f1.text_field :employmentDate, class: "form-control" %>
			    	<% else %>
			    		<%= f1.text_field :employmentDate, class: "form-control", value: l(@user.receptionist.employmentDate, format: "%d.%m.%Y %H:%M").humanize %>
			    	<% end %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>
		<% end %>

	  <div class="actions">
	    <%= f.submit "Zarejestruj recepcjonistkę", class: "btn btn-primary" %>
	  </div>
	<% end %>
</div>
<p><%= link_to "Powrót do recepcjonistek", receptionists_index_path, class: "linkto" %></p>

app/views/receptionists/index.html.erb
<h1>Recepcjonistki</h1>

<div class="addlinkdiv">
	<p><%= link_to "Dodaj nową recepcjonistę", receptionists_new_path, class: "addlink"%></p>
</div>

<div id="serarchdiv">
	<%= form_tag receptionists_index_path, :method => :get, :class => "navbar-form navbar-left", :role => "search", :id => "receptionists_search", :enforce_utf8 => false do %>
		<table class="table" id="searchtable">
			<thead>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Wyszukaj:</th>
			</thead>
			<tbody>
				<tr>
					<td>
					  <%= text_field_tag :search, params[:search], placeholder: "Wyszukaj", class: "form-control" %>
					</td>
		   	</tr>
			</tbody>
		</table>
	<% end %>
</div>

<div id="receptionists">
	<%= render "receptionists" %>
</div>

app/views/receptionists/index.js.erb
$('#receptionists').html('<%= escape_javascript(render("receptionists")) %>');

app/views/receptionists/new.html.erb
<h1>Rejestracja nowej recepcjonistki</h1>
<% if @user.errors.any? %>
	<% @user.attributes.keys.each do |key| %>
		<% if @user.errors.full_messages_for(key.to_sym).length > 0  %>
			<%= @user.errors.full_messages_for(key.to_sym).first %> <br />
		<% end %>
	<% end %>
<% end %>
<% if @user.receptionist.errors.full_messages.any? %>
	<% @user.receptionist.attributes.keys.each do |key| %>
		<% if @user.receptionist.errors.full_messages_for(key.to_sym).length > 0  %>
			<%= @user.receptionist.errors.full_messages_for(key.to_sym).first %> <br />
		<% end %>
	<% end %>
<% end %>

<div id="receptionistregistrationform">

	<%= form_for @user, url: receptionists_create_path, :method => :post, html: { autocomplete: 'off' } do |f| %>
		<div class="form-group">
	    <%= f.label :Imię %><br />
	    <%= f.text_field :name, autofocus: true, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Nazwisko %><br />
	    <%= f.text_field :surname, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Płeć %><br />
	    <%= select_tag :sex, options_for_select([['Kobieta', 0], ['Mężczyzna', 1]], @user.sex),  class: "form-control" %>
	  </div>


	  <div class="form-group">
	    <%= f.label :Login %><br />
	    <%= f.text_field :login, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label 'E-mail' %><br />
	    <%= f.email_field :email, class: "form-control" %>
	  </div>

		<div class="form-group">
	    <%= f.label :Miasto %><br />
	  	<%= f.autocomplete_field :city ,autocomplete_city_name_admins_path,'data-auto-focus' => true, class: "form-control", :id_element => '#post_city_id', "data-auto-label" => "Sorry, nothing found.", :append_to => "#autocompleteresult"%>
	  	<%= hidden_field(:post, :city_id, :value => get_city_id(@user.city))%>
	  	<div id="autocompleteresult">
	  	</div>
	  </div>

	  <div class="form-group">
	    <%= f.label :Ulica %><br />
	    <%= f.text_field :street, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label 'Nr domu i mieszkania' %><br />
	    <%= f.text_field :address, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Pesel %><br />
	    <%= f.text_field :pesel, class: "form-control" %>
	  </div>

	  <div class="form-group">
	    <%= f.label :Telefon %><br />
	    <%= f.text_field :phone, class: "form-control" %>
	  </div>

		<%= f.fields_for :receptionist do |f1| %>
		  <div class="form-group">
		    <%= f1.label :Stanowisko %>
		    <%= f1.text_field :position, class: "form-control" %>
		  </div>

		  <div class="form-group">
		    <%= f1.label "Data zatrudnienia" %>
		    	<div class='input-group date' id='datetimepicker'>
		    		<% if @user.receptionist.employmentDate.nil? %>
			    		<%= f1.text_field :employmentDate, class: "form-control" %>
			    	<% else %>
			    		<%= f1.text_field :employmentDate, class: "form-control", value: l(@user.receptionist.employmentDate, format: "%d.%m.%Y %H:%M").humanize %>
			    	<% end %>
		    		<span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
		  </div>
		<% end %>

	  <div class="actions">
	    <%= f.submit "Zarejestruj recepcjonistkę", class: "btn btn-primary" %>
	  </div>
	<% end %>
</div>
<p><%= link_to "Powrót do recepcjonistek", receptionists_index_path, class: "linkto" %></p>

app/views/receptionists/show.html.erb
<h1>Recepcjonistka <%= @user.name %> <%= @user.surname %></h1>

<div id="usershowdiv">
	<table class="table table-hover">
	    <tr>
	    	<td id="firstrow" class="col-md-4">Login</td>
	     	<td id="firstrow"><%= @user.login %></td>
	    </tr>
	    <tr>
	    	<td>E-mail</td>
	    	<td><%= @user.email %></td>
	    </tr>
	    <tr>
	    	<td>Telefon</td>
	    	<td><%= @user.phone %></td>
	    </tr>
	    <tr>
	    	<td>Pesel</td>
	    	<td><%= @user.pesel %></td>
	    </tr>
	    <tr>
	    	<td>Płeć</td>
	     	<td><%= @user.sex == 0 ? "Kobieta" : "Mężczyzna" %></td>
	    </tr>
	    <tr>
	    	<td>Adres</td>
	     	<td><%= @user.city.to_s %>, <%= @user.street %> <%= @user.address %></td>
	    </tr>
	    <tr>
	    	<td>Stanowisko</td>
	     	<td><%= @user.receptionist.position %></td>
	    </tr>
	    <tr>
	    	<td>Data zatrudnienia</td>
	     	<td><%= @user.receptionist.employmentDate %></td>
	    </tr>
	    <% if @user.receptionist.dismissalDate %>
	    	<tr>
	    	<td>Data zwonienia</td>
	     	<td><%= @user.receptionist.dismissalDate %></td>
	    </tr>
	    <% end %>
	</table>
</div>

<p><%= link_to "Powrót do recepcjonistek", receptionists_index_path, class: "linkto" %></p>